Fixed for HttpUpgradeTest and AsyncInputTest that occasionally caused failures - Since blocking and non-blocking reads can occur simultaneously, the blocking read is removed. - Details: https://jakarta.ee/specifications/servlet/6.1/jakarta-servlet-spec-6.1#upgrade-processing `The Application Developer has the responsibility for thread safe access to the ServletInputStream and ServletOutputStream while processing HTTP upgrade.`
https://ci.eclipse.org/glassfish/view/Grizzly/job/Grizzly-master_nightly/org.glassfish.grizzly$grizzly-http-servlet/3135/testReport/junit/
```
expected:<Hell[]oWorld> but was:<Hell[l]oWorld>

Stack Trace

junit.framework.ComparisonFailure: expected:<Hell[]oWorld> but was:<Hell[l]oWorld>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:260)
	at org.glassfish.grizzly.servlet.httpupgrade.HttpUpgradeTest.testEchoProtocolUpgrade(HttpUpgradeTest.java:131)
```