(Trivial) Fixed BindExceptions of some testcases
- Here are some examples:
```
[ERROR] org.glassfish.grizzly.portunif.BasicPUTest.protocolsXYZ -- Time elapsed: 0.007 s <<< ERROR!
java.net.BindException: Cannot bind to requested socket address 0.0.0.0/0.0.0.0:17400
	at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bindToChannelAndAddress(TCPNIOBindingHandler.java:101)
	at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bind(TCPNIOBindingHandler.java:65)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:227)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:218)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:194)
	at org.glassfish.grizzly.portunif.BasicPUTest.protocolsXYZ(BasicPUTest.java:95)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
...
```
```
java.net.BindException: Couldn't bind to any port in the range `18300:18300`.
	at org.glassfish.grizzly.AbstractBindingHandler.bind(AbstractBindingHandler.java:149)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:254)
	at org.glassfish.grizzly.http.server.NetworkListener.start(NetworkListener.java:779)
	at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:234)
	at org.glassfish.grizzly.http2.HttpInputStreamsTest.doTest(HttpInputStreamsTest.java:1150)
...
```
- Removed unused codes